"""mcp: agent-bound api keys, ai_searchable documents, mcp tool approvals

Revision ID: a888d11bd47d
Revises: bdc4e4b7de36
Create Date: 2026-08-07 10:41:49.506819
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import app.core.db  # portable column types referenced below


revision: str = 'a888d11bd47d'
down_revision: str | Sequence[str] | None = 'bdc4e4b7de36'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_tool_approvals',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('api_key_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('agent_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('tool_key', sa.String(length=120), nullable=False),
    sa.Column('tool_input', app.core.db.PortableJSON(), nullable=False),
    sa.Column('params_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('requested_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('decided_by', app.core.db.GUID(length=36), nullable=True),
    sa.Column('decided_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_mcp_tool_approvals_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], name=op.f('fk_mcp_tool_approvals_api_key_id_api_keys'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_mcp_tool_approvals_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mcp_tool_approvals'))
    )
    op.create_index(op.f('ix_mcp_tool_approvals_agent_id'), 'mcp_tool_approvals', ['agent_id'], unique=False)
    op.create_index(op.f('ix_mcp_tool_approvals_api_key_id'), 'mcp_tool_approvals', ['api_key_id'], unique=False)
    op.create_index('ix_mcp_tool_approvals_lookup', 'mcp_tool_approvals', ['api_key_id', 'tool_key', 'params_hash', 'status'], unique=False)
    op.create_index(op.f('ix_mcp_tool_approvals_workspace_id'), 'mcp_tool_approvals', ['workspace_id'], unique=False)
    op.create_index('ix_mcp_tool_approvals_ws_status', 'mcp_tool_approvals', ['workspace_id', 'status'], unique=False)
    op.add_column('api_keys', sa.Column('agent_id', app.core.db.GUID(length=36), nullable=True))
    op.create_index(op.f('ix_api_keys_agent_id'), 'api_keys', ['agent_id'], unique=False)
    op.create_foreign_key(op.f('fk_api_keys_agent_id_agents'), 'api_keys', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    # Existing documents stay AI-searchable: the server default backfills them,
    # and the model default keeps new rows true.
    op.add_column(
        'documents',
        sa.Column('ai_searchable', sa.Boolean(), server_default=sa.true(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'ai_searchable')
    op.drop_constraint(op.f('fk_api_keys_agent_id_agents'), 'api_keys', type_='foreignkey')
    op.drop_index(op.f('ix_api_keys_agent_id'), table_name='api_keys')
    op.drop_column('api_keys', 'agent_id')
    op.drop_index('ix_mcp_tool_approvals_ws_status', table_name='mcp_tool_approvals')
    op.drop_index(op.f('ix_mcp_tool_approvals_workspace_id'), table_name='mcp_tool_approvals')
    op.drop_index('ix_mcp_tool_approvals_lookup', table_name='mcp_tool_approvals')
    op.drop_index(op.f('ix_mcp_tool_approvals_api_key_id'), table_name='mcp_tool_approvals')
    op.drop_index(op.f('ix_mcp_tool_approvals_agent_id'), table_name='mcp_tool_approvals')
    op.drop_table('mcp_tool_approvals')
    # ### end Alembic commands ###
