"""integrations: connections + app credentials

Revision ID: b485d38185bf
Revises: a888d11bd47d
Create Date: 2026-08-07 13:19:56.106099
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import app.core.db  # portable column types referenced below


revision: str = 'b485d38185bf'
down_revision: str | Sequence[str] | None = 'a888d11bd47d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_app_credentials',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('client_id', sa.String(length=320), nullable=False),
    sa.Column('client_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('extra', app.core.db.PortableJSON(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_integration_app_credentials_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_app_credentials')),
    sa.UniqueConstraint('workspace_id', 'provider', name='uq_integration_credentials_provider')
    )
    op.create_index(op.f('ix_integration_app_credentials_workspace_id'), 'integration_app_credentials', ['workspace_id'], unique=False)
    op.create_table('integration_connections',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('account_label', sa.String(length=320), nullable=True),
    sa.Column('scopes', app.core.db.PortableJSON(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('meta', app.core.db.PortableJSON(), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_integration_connections_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_connections'))
    )
    op.create_index(op.f('ix_integration_connections_provider'), 'integration_connections', ['provider'], unique=False)
    op.create_index(op.f('ix_integration_connections_workspace_id'), 'integration_connections', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integration_connections_workspace_id'), table_name='integration_connections')
    op.drop_index(op.f('ix_integration_connections_provider'), table_name='integration_connections')
    op.drop_table('integration_connections')
    op.drop_index(op.f('ix_integration_app_credentials_workspace_id'), table_name='integration_app_credentials')
    op.drop_table('integration_app_credentials')
    # ### end Alembic commands ###
