"""dap2 tours v2 checklists surveys

Revision ID: bdc4e4b7de36
Revises: f1639ab942db
Create Date: 2026-07-31 14:15:18.014384
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import app.core.db  # portable column types referenced below


revision: str = 'bdc4e4b7de36'
down_revision: str | Sequence[str] | None = 'f1639ab942db'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklists',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('items', app.core.db.PortableJSON(), nullable=False),
    sa.Column('trigger', app.core.db.PortableJSON(), nullable=False),
    sa.Column('audience', app.core.db.PortableJSON(), nullable=False),
    sa.Column('theme', app.core.db.PortableJSON(), nullable=False),
    sa.Column('launcher', app.core.db.PortableJSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', app.core.db.GUID(length=36), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_checklists_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_checklists_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklists'))
    )
    op.create_index(op.f('ix_checklists_workspace_id'), 'checklists', ['workspace_id'], unique=False)
    op.create_table('surveys',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('questions', app.core.db.PortableJSON(), nullable=False),
    sa.Column('presentation', sa.String(length=20), nullable=False),
    sa.Column('trigger', app.core.db.PortableJSON(), nullable=False),
    sa.Column('audience', app.core.db.PortableJSON(), nullable=False),
    sa.Column('schedule', app.core.db.PortableJSON(), nullable=False),
    sa.Column('frequency', app.core.db.PortableJSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('theme', app.core.db.PortableJSON(), nullable=False),
    sa.Column('thanks_message', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', app.core.db.GUID(length=36), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_surveys_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_surveys_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_surveys'))
    )
    op.create_index(op.f('ix_surveys_workspace_id'), 'surveys', ['workspace_id'], unique=False)
    op.create_table('checklist_progress',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('checklist_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('contact_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('item_state', app.core.db.PortableJSON(), nullable=False),
    sa.Column('dismissed_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('completed_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], name=op.f('fk_checklist_progress_checklist_id_checklists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_checklist_progress_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklist_progress')),
    sa.UniqueConstraint('checklist_id', 'contact_id', name='uq_checklist_progress_checklist_contact')
    )
    op.create_index(op.f('ix_checklist_progress_checklist_id'), 'checklist_progress', ['checklist_id'], unique=False)
    op.create_index(op.f('ix_checklist_progress_contact_id'), 'checklist_progress', ['contact_id'], unique=False)
    op.create_index(op.f('ix_checklist_progress_workspace_id'), 'checklist_progress', ['workspace_id'], unique=False)
    op.create_table('survey_responses',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('survey_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('contact_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('answers', app.core.db.PortableJSON(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('meta', app.core.db.PortableJSON(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_survey_responses_survey_id_surveys'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_survey_responses_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_survey_responses'))
    )
    op.create_index(op.f('ix_survey_responses_contact_id'), 'survey_responses', ['contact_id'], unique=False)
    op.create_index('ix_survey_responses_survey_created', 'survey_responses', ['survey_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_survey_responses_survey_id'), 'survey_responses', ['survey_id'], unique=False)
    op.create_index(op.f('ix_survey_responses_workspace_id'), 'survey_responses', ['workspace_id'], unique=False)
    # NOTE: `ix_chunks_fts` and `ix_contacts_name_trgm` are expression indexes created
    # at startup by app.core.db.ensure_pg_indexes, not by metadata; autogenerate cannot
    # see them and proposes dropping them. Deliberately not touched here.
    op.add_column('tours', sa.Column('kind', sa.String(length=20), server_default='flow', nullable=False))
    op.add_column('tours', sa.Column('schedule', app.core.db.PortableJSON(), server_default='{}', nullable=False))
    op.add_column('tours', sa.Column('frequency', app.core.db.PortableJSON(), server_default='{}', nullable=False))
    op.add_column('tours', sa.Column('priority', sa.Integer(), server_default='0', nullable=False))
    op.add_column('tours', sa.Column('settings', app.core.db.PortableJSON(), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tours', 'settings')
    op.drop_column('tours', 'priority')
    op.drop_column('tours', 'frequency')
    op.drop_column('tours', 'schedule')
    op.drop_column('tours', 'kind')
    op.drop_index(op.f('ix_survey_responses_workspace_id'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_survey_id'), table_name='survey_responses')
    op.drop_index('ix_survey_responses_survey_created', table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_contact_id'), table_name='survey_responses')
    op.drop_table('survey_responses')
    op.drop_index(op.f('ix_checklist_progress_workspace_id'), table_name='checklist_progress')
    op.drop_index(op.f('ix_checklist_progress_contact_id'), table_name='checklist_progress')
    op.drop_index(op.f('ix_checklist_progress_checklist_id'), table_name='checklist_progress')
    op.drop_table('checklist_progress')
    op.drop_index(op.f('ix_surveys_workspace_id'), table_name='surveys')
    op.drop_table('surveys')
    op.drop_index(op.f('ix_checklists_workspace_id'), table_name='checklists')
    op.drop_table('checklists')
    # ### end Alembic commands ###
