"""p0 inbox parity: working hours, collaboration, saved views,
custom attributes, contact merge/blocking/import

Revision ID: e133372bfc35
Revises: bdc4e4b7de36
Create Date: 2026-08-07 10:52:00.662593
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import app.core.db  # portable column types referenced below


revision: str = 'e133372bfc35'
down_revision: str | Sequence[str] | None = 'bdc4e4b7de36'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_imports',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('filename', sa.String(length=400), nullable=False),
    sa.Column('file_key', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mapping', app.core.db.PortableJSON(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('errors', app.core.db.PortableJSON(), nullable=False),
    sa.Column('started_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('completed_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by', app.core.db.GUID(length=36), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_contact_imports_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_contact_imports_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_imports'))
    )
    op.create_index(op.f('ix_contact_imports_workspace_id'), 'contact_imports', ['workspace_id'], unique=False)
    op.create_table('conversation_participants',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('conversation_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('user_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('muted', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversation_participants_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_conversation_participants_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_participants')),
    sa.UniqueConstraint('conversation_id', 'user_id', name='uq_conv_participant')
    )
    op.create_index(op.f('ix_conversation_participants_conversation_id'), 'conversation_participants', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_participants_user_id'), 'conversation_participants', ['user_id'], unique=False)
    op.create_index(op.f('ix_conversation_participants_workspace_id'), 'conversation_participants', ['workspace_id'], unique=False)
    op.create_table('custom_attribute_definitions',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('attribute_model', sa.String(length=20), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attribute_type', sa.String(length=20), nullable=False),
    sa.Column('options', app.core.db.PortableJSON(), nullable=False),
    sa.Column('default_value', app.core.db.PortableJSON(), nullable=True),
    sa.Column('regex_pattern', sa.String(length=300), nullable=True),
    sa.Column('regex_cue', sa.String(length=300), nullable=True),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('shown_on_front', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_custom_attribute_definitions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_attribute_definitions')),
    sa.UniqueConstraint('workspace_id', 'attribute_model', 'key', name='uq_custom_attr_ws_model_key')
    )
    op.create_index(op.f('ix_custom_attribute_definitions_workspace_id'), 'custom_attribute_definitions', ['workspace_id'], unique=False)
    op.create_table('mentions',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('conversation_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('message_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('user_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('author_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('read_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_mentions_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mentions_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_mentions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mentions'))
    )
    op.create_index(op.f('ix_mentions_conversation_id'), 'mentions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_mentions_message_id'), 'mentions', ['message_id'], unique=False)
    op.create_index(op.f('ix_mentions_user_id'), 'mentions', ['user_id'], unique=False)
    op.create_index(op.f('ix_mentions_workspace_id'), 'mentions', ['workspace_id'], unique=False)
    op.create_table('saved_views',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('query', app.core.db.PortableJSON(), nullable=False),
    sa.Column('icon', sa.String(length=20), nullable=True),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('created_by', app.core.db.GUID(length=36), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_saved_views_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_saved_views_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_views'))
    )
    op.create_index(op.f('ix_saved_views_created_by'), 'saved_views', ['created_by'], unique=False)
    op.create_index(op.f('ix_saved_views_workspace_id'), 'saved_views', ['workspace_id'], unique=False)
    op.create_table('working_hours',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('inbox_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('closed_all_day', sa.Boolean(), nullable=False),
    sa.Column('open_all_day', sa.Boolean(), nullable=False),
    sa.Column('open_minute', sa.Integer(), nullable=False),
    sa.Column('close_minute', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['inbox_id'], ['inboxes.id'], name=op.f('fk_working_hours_inbox_id_inboxes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_working_hours_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_working_hours')),
    sa.UniqueConstraint('inbox_id', 'day_of_week', name='uq_working_hours_inbox_day')
    )
    op.create_index(op.f('ix_working_hours_inbox_id'), 'working_hours', ['inbox_id'], unique=False)
    op.create_index(op.f('ix_working_hours_workspace_id'), 'working_hours', ['workspace_id'], unique=False)
    # server_default backfills existing rows, then it is dropped so the column
    # matches the model exactly (`alembic check` must report no drift).
    op.add_column(
        'contacts',
        sa.Column('blocked', sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    op.alter_column('contacts', 'blocked', server_default=None)
    op.add_column('contacts', sa.Column('merged_into_id', app.core.db.GUID(length=36), nullable=True))
    op.create_index(op.f('ix_contacts_merged_into_id'), 'contacts', ['merged_into_id'], unique=False)
    op.add_column(
        'sla_policies',
        sa.Column(
            'only_during_business_hours',
            sa.Boolean(),
            server_default=sa.false(),
            nullable=False,
        ),
    )
    op.alter_column('sla_policies', 'only_during_business_hours', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sla_policies', 'only_during_business_hours')
    op.drop_index(op.f('ix_contacts_merged_into_id'), table_name='contacts')
    op.drop_column('contacts', 'merged_into_id')
    op.drop_column('contacts', 'blocked')
    op.drop_index(op.f('ix_working_hours_workspace_id'), table_name='working_hours')
    op.drop_index(op.f('ix_working_hours_inbox_id'), table_name='working_hours')
    op.drop_table('working_hours')
    op.drop_index(op.f('ix_saved_views_workspace_id'), table_name='saved_views')
    op.drop_index(op.f('ix_saved_views_created_by'), table_name='saved_views')
    op.drop_table('saved_views')
    op.drop_index(op.f('ix_mentions_workspace_id'), table_name='mentions')
    op.drop_index(op.f('ix_mentions_user_id'), table_name='mentions')
    op.drop_index(op.f('ix_mentions_message_id'), table_name='mentions')
    op.drop_index(op.f('ix_mentions_conversation_id'), table_name='mentions')
    op.drop_table('mentions')
    op.drop_index(op.f('ix_custom_attribute_definitions_workspace_id'), table_name='custom_attribute_definitions')
    op.drop_table('custom_attribute_definitions')
    op.drop_index(op.f('ix_conversation_participants_workspace_id'), table_name='conversation_participants')
    op.drop_index(op.f('ix_conversation_participants_user_id'), table_name='conversation_participants')
    op.drop_index(op.f('ix_conversation_participants_conversation_id'), table_name='conversation_participants')
    op.drop_table('conversation_participants')
    op.drop_index(op.f('ix_contact_imports_workspace_id'), table_name='contact_imports')
    op.drop_table('contact_imports')
    # ### end Alembic commands ###
