"""channels, sla, macros, campaigns, connectors, search analytics

Revision ID: f1639ab942db
Revises: f3d56cbfd7a7
Create Date: 2026-07-31 11:24:30.081671
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import app.core.db  # portable column types referenced below


revision: str = 'f1639ab942db'
down_revision: str | Sequence[str] | None = 'f3d56cbfd7a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macros',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('actions', app.core.db.PortableJSON(), nullable=False),
    sa.Column('visibility', sa.String(length=10), nullable=False),
    sa.Column('created_by', app.core.db.GUID(length=36), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_macros_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_macros_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_macros'))
    )
    op.create_index(op.f('ix_macros_workspace_id'), 'macros', ['workspace_id'], unique=False)
    op.create_table('message_feedback',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('conversation_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('message_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('actor_type', sa.String(length=10), nullable=False),
    sa.Column('actor_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('rating', sa.String(length=4), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_message_feedback_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_feedback')),
    sa.UniqueConstraint('message_id', 'actor_type', 'actor_id', name='uq_message_feedback_actor')
    )
    op.create_index(op.f('ix_message_feedback_conversation_id'), 'message_feedback', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_feedback_message_id'), 'message_feedback', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_feedback_workspace_id'), 'message_feedback', ['workspace_id'], unique=False)
    op.create_table('search_queries',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('top_score', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_search_queries_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_queries'))
    )
    op.create_index(op.f('ix_search_queries_workspace_id'), 'search_queries', ['workspace_id'], unique=False)
    op.create_index('ix_search_queries_ws_created', 'search_queries', ['workspace_id', 'created_at'], unique=False)
    op.create_table('sla_policies',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('first_response_minutes', sa.Integer(), nullable=True),
    sa.Column('next_response_minutes', sa.Integer(), nullable=True),
    sa.Column('resolution_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_sla_policies_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sla_policies'))
    )
    op.create_index(op.f('ix_sla_policies_workspace_id'), 'sla_policies', ['workspace_id'], unique=False)
    op.create_table('applied_slas',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('conversation_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('sla_policy_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['sla_policy_id'], ['sla_policies.id'], name=op.f('fk_applied_slas_sla_policy_id_sla_policies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_applied_slas_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applied_slas')),
    sa.UniqueConstraint('conversation_id', name='uq_applied_slas_conversation')
    )
    op.create_index(op.f('ix_applied_slas_conversation_id'), 'applied_slas', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_applied_slas_sla_policy_id'), 'applied_slas', ['sla_policy_id'], unique=False)
    op.create_index(op.f('ix_applied_slas_workspace_id'), 'applied_slas', ['workspace_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('campaign_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('inbox_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('sender_user_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('audience', app.core.db.PortableJSON(), nullable=False),
    sa.Column('trigger_rules', app.core.db.PortableJSON(), nullable=False),
    sa.Column('scheduled_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['inbox_id'], ['inboxes.id'], name=op.f('fk_campaigns_inbox_id_inboxes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_campaigns_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_index(op.f('ix_campaigns_inbox_id'), 'campaigns', ['inbox_id'], unique=False)
    op.create_index(op.f('ix_campaigns_workspace_id'), 'campaigns', ['workspace_id'], unique=False)
    op.create_index('ix_campaigns_ws_type_status', 'campaigns', ['workspace_id', 'campaign_type', 'status'], unique=False)
    op.create_table('sla_events',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('applied_sla_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('conversation_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=10), nullable=False),
    sa.Column('meta', app.core.db.PortableJSON(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['applied_sla_id'], ['applied_slas.id'], name=op.f('fk_sla_events_applied_sla_id_applied_slas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_sla_events_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sla_events'))
    )
    op.create_index(op.f('ix_sla_events_applied_sla_id'), 'sla_events', ['applied_sla_id'], unique=False)
    op.create_index(op.f('ix_sla_events_conversation_id'), 'sla_events', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_sla_events_workspace_id'), 'sla_events', ['workspace_id'], unique=False)
    # NOTE: autogenerate wanted to drop ix_chunks_fts / ix_contacts_name_trgm —
    # those are expression indexes owned by app.core.db.ensure_pg_indexes (not
    # model metadata) and must stay. Removed from this migration by hand.
    op.add_column('knowledge_sources', sa.Column('secrets_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_sources', 'secrets_encrypted')
    op.drop_index(op.f('ix_sla_events_workspace_id'), table_name='sla_events')
    op.drop_index(op.f('ix_sla_events_conversation_id'), table_name='sla_events')
    op.drop_index(op.f('ix_sla_events_applied_sla_id'), table_name='sla_events')
    op.drop_table('sla_events')
    op.drop_index('ix_campaigns_ws_type_status', table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_workspace_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_inbox_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_applied_slas_workspace_id'), table_name='applied_slas')
    op.drop_index(op.f('ix_applied_slas_sla_policy_id'), table_name='applied_slas')
    op.drop_index(op.f('ix_applied_slas_conversation_id'), table_name='applied_slas')
    op.drop_table('applied_slas')
    op.drop_index(op.f('ix_sla_policies_workspace_id'), table_name='sla_policies')
    op.drop_table('sla_policies')
    op.drop_index('ix_search_queries_ws_created', table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_workspace_id'), table_name='search_queries')
    op.drop_table('search_queries')
    op.drop_index(op.f('ix_message_feedback_workspace_id'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_message_id'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_conversation_id'), table_name='message_feedback')
    op.drop_table('message_feedback')
    op.drop_index(op.f('ix_macros_workspace_id'), table_name='macros')
    op.drop_table('macros')
    # ### end Alembic commands ###
