"""initial schema

Revision ID: f3d56cbfd7a7
Revises: 
Create Date: 2026-07-31 09:34:58.028872
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import app.core.db  # portable column types referenced below


revision: str = 'f3d56cbfd7a7'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table('users',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('preferences', app.core.db.PortableJSON(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('user_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('expires_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', app.core.db.GUID(length=36), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('created_by', app.core.db.GUID(length=36), nullable=True),
    sa.Column('settings', app.core.db.PortableJSON(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_workspaces_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_table('agents',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('avatar_emoji', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('model_ref', sa.String(length=300), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('settings', app.core.db.PortableJSON(), nullable=False),
    sa.Column('tools', app.core.db.PortableJSON(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_agents_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    op.create_index(op.f('ix_agents_workspace_id'), 'agents', ['workspace_id'], unique=False)
    op.create_table('ai_providers',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('meta', app.core.db.PortableJSON(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_ai_providers_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_providers'))
    )
    op.create_index(op.f('ix_ai_providers_workspace_id'), 'ai_providers', ['workspace_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('hashed_key', sa.String(length=64), nullable=False),
    sa.Column('scopes', app.core.db.PortableJSON(), nullable=False),
    sa.Column('created_by', app.core.db.GUID(length=36), nullable=True),
    sa.Column('last_used_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_api_keys_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_api_keys_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys'))
    )
    op.create_index(op.f('ix_api_keys_hashed_key'), 'api_keys', ['hashed_key'], unique=True)
    op.create_index(op.f('ix_api_keys_workspace_id'), 'api_keys', ['workspace_id'], unique=False)
    op.create_table('article_collections',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=20), nullable=True),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_article_collections_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_collections')),
    sa.UniqueConstraint('workspace_id', 'slug', name='uq_article_collections_ws_slug')
    )
    op.create_index(op.f('ix_article_collections_workspace_id'), 'article_collections', ['workspace_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_label', sa.String(length=200), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('meta', app.core.db.PortableJSON(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_audit_logs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.create_index('ix_audit_logs_ws_created', 'audit_logs', ['workspace_id', 'created_at'], unique=False)
    op.create_table('automation_rules',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('conditions', app.core.db.PortableJSON(), nullable=False),
    sa.Column('actions', app.core.db.PortableJSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('created_by', app.core.db.GUID(length=36), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_automation_rules_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_automation_rules_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_rules'))
    )
    op.create_index(op.f('ix_automation_rules_workspace_id'), 'automation_rules', ['workspace_id'], unique=False)
    op.create_index('ix_automation_rules_ws_event_enabled', 'automation_rules', ['workspace_id', 'event', 'enabled'], unique=False)
    op.create_table('canned_responses',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('shortcut', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_by', app.core.db.GUID(length=36), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_canned_responses_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_canned_responses_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canned_responses')),
    sa.UniqueConstraint('workspace_id', 'shortcut', name='uq_canned_responses_ws_shortcut')
    )
    op.create_index(op.f('ix_canned_responses_workspace_id'), 'canned_responses', ['workspace_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('attributes', app.core.db.PortableJSON(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_contacts_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts')),
    sa.UniqueConstraint('workspace_id', 'external_id', name='uq_contacts_ws_external')
    )
    op.create_index(op.f('ix_contacts_workspace_id'), 'contacts', ['workspace_id'], unique=False)
    op.create_index('ix_contacts_ws_email', 'contacts', ['workspace_id', 'email'], unique=False)
    op.create_index('ix_contacts_ws_last_seen', 'contacts', ['workspace_id', 'last_seen_at'], unique=False)
    op.create_table('conversation_counters',
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_conversation_counters_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', name=op.f('pk_conversation_counters'))
    )
    op.create_table('custom_actions',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('headers', app.core.db.PortableJSON(), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=True),
    sa.Column('params_schema', app.core.db.PortableJSON(), nullable=False),
    sa.Column('timeout_s', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_custom_actions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_actions'))
    )
    op.create_index(op.f('ix_custom_actions_workspace_id'), 'custom_actions', ['workspace_id'], unique=False)
    op.create_table('custom_roles',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('permissions', app.core.db.PortableJSON(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_custom_roles_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_roles')),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_custom_roles_ws_name')
    )
    op.create_index(op.f('ix_custom_roles_workspace_id'), 'custom_roles', ['workspace_id'], unique=False)
    op.create_table('inboxes',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('channel_type', sa.String(length=30), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', app.core.db.PortableJSON(), nullable=False),
    sa.Column('secrets_encrypted', sa.Text(), nullable=True),
    sa.Column('widget_key', sa.String(length=80), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_inboxes_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inboxes'))
    )
    op.create_index(op.f('ix_inboxes_widget_key'), 'inboxes', ['widget_key'], unique=True)
    op.create_index(op.f('ix_inboxes_workspace_id'), 'inboxes', ['workspace_id'], unique=False)
    op.create_table('knowledge_sources',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('config', app.core.db.PortableJSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('last_synced_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_knowledge_sources_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_sources'))
    )
    op.create_index(op.f('ix_knowledge_sources_workspace_id'), 'knowledge_sources', ['workspace_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('user_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('meta', app.core.db.PortableJSON(), nullable=False),
    sa.Column('read_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_notifications_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_workspace_id'), 'notifications', ['workspace_id'], unique=False)
    op.create_index('ix_notifications_ws_user_read', 'notifications', ['workspace_id', 'user_id', 'read_at'], unique=False)
    op.create_table('segments',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('filters', app.core.db.PortableJSON(), nullable=False),
    sa.Column('created_by', app.core.db.GUID(length=36), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_segments_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_segments_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_segments'))
    )
    op.create_index(op.f('ix_segments_workspace_id'), 'segments', ['workspace_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_tags_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_tags_ws_name')
    )
    op.create_index(op.f('ix_tags_workspace_id'), 'tags', ['workspace_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_teams_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_teams_ws_name')
    )
    op.create_index(op.f('ix_teams_workspace_id'), 'teams', ['workspace_id'], unique=False)
    op.create_table('tours',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger', app.core.db.PortableJSON(), nullable=False),
    sa.Column('audience', app.core.db.PortableJSON(), nullable=False),
    sa.Column('steps', app.core.db.PortableJSON(), nullable=False),
    sa.Column('theme', app.core.db.PortableJSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', app.core.db.GUID(length=36), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_tours_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_tours_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tours'))
    )
    op.create_index(op.f('ix_tours_workspace_id'), 'tours', ['workspace_id'], unique=False)
    op.create_table('webhooks',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('secret', sa.String(length=120), nullable=False),
    sa.Column('events', app.core.db.PortableJSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_webhooks_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhooks'))
    )
    op.create_index(op.f('ix_webhooks_workspace_id'), 'webhooks', ['workspace_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('conversation_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('agent_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('trigger_message_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('started_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('lease_expires_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('messages_snapshot', app.core.db.PortableJSON(), nullable=True),
    sa.Column('pending_tool_call', app.core.db.PortableJSON(), nullable=True),
    sa.Column('citations', app.core.db.PortableJSON(), nullable=False),
    sa.Column('reply_message_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_runs_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_agent_runs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index(op.f('ix_agent_runs_agent_id'), 'agent_runs', ['agent_id'], unique=False)
    op.create_index('ix_agent_runs_conversation', 'agent_runs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_workspace_id'), 'agent_runs', ['workspace_id'], unique=False)
    op.create_index('ix_agent_runs_ws_status', 'agent_runs', ['workspace_id', 'status'], unique=False)
    op.create_table('ai_models',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('provider_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('model_key', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('modality', sa.String(length=20), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], name=op.f('fk_ai_models_provider_id_ai_providers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_ai_models_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_models')),
    sa.UniqueConstraint('provider_id', 'model_key', name='uq_ai_models_provider_model')
    )
    op.create_index(op.f('ix_ai_models_provider_id'), 'ai_models', ['provider_id'], unique=False)
    op.create_index(op.f('ix_ai_models_workspace_id'), 'ai_models', ['workspace_id'], unique=False)
    op.create_table('articles',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('collection_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('author_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('published_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('meta', app.core.db.PortableJSON(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_articles_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['collection_id'], ['article_collections.id'], name=op.f('fk_articles_collection_id_article_collections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_articles_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles')),
    sa.UniqueConstraint('workspace_id', 'slug', name='uq_articles_ws_slug')
    )
    op.create_index(op.f('ix_articles_collection_id'), 'articles', ['collection_id'], unique=False)
    op.create_index(op.f('ix_articles_workspace_id'), 'articles', ['workspace_id'], unique=False)
    op.create_table('contact_events',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('contact_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('meta', app.core.db.PortableJSON(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_contact_events_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_contact_events_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_events'))
    )
    op.create_index('ix_contact_events_contact_created', 'contact_events', ['contact_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_contact_events_contact_id'), 'contact_events', ['contact_id'], unique=False)
    op.create_index(op.f('ix_contact_events_workspace_id'), 'contact_events', ['workspace_id'], unique=False)
    op.create_table('contact_inboxes',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('contact_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('inbox_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=320), nullable=False),
    sa.Column('hmac_verified', sa.Boolean(), nullable=False),
    sa.Column('meta', app.core.db.PortableJSON(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_contact_inboxes_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inbox_id'], ['inboxes.id'], name=op.f('fk_contact_inboxes_inbox_id_inboxes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_contact_inboxes_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_inboxes')),
    sa.UniqueConstraint('inbox_id', 'source_id', name='uq_contact_inboxes_inbox_source')
    )
    op.create_index(op.f('ix_contact_inboxes_contact_id'), 'contact_inboxes', ['contact_id'], unique=False)
    op.create_index(op.f('ix_contact_inboxes_inbox_id'), 'contact_inboxes', ['inbox_id'], unique=False)
    op.create_index(op.f('ix_contact_inboxes_workspace_id'), 'contact_inboxes', ['workspace_id'], unique=False)
    op.create_table('contact_notes',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('contact_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('author_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_contact_notes_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_contact_notes_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_contact_notes_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_notes'))
    )
    op.create_index(op.f('ix_contact_notes_contact_id'), 'contact_notes', ['contact_id'], unique=False)
    op.create_index(op.f('ix_contact_notes_workspace_id'), 'contact_notes', ['workspace_id'], unique=False)
    op.create_table('contact_tags',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('contact_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('tag_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_contact_tags_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_contact_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_contact_tags_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_tags')),
    sa.UniqueConstraint('contact_id', 'tag_id', name='uq_contact_tags_pair')
    )
    op.create_index(op.f('ix_contact_tags_contact_id'), 'contact_tags', ['contact_id'], unique=False)
    op.create_index(op.f('ix_contact_tags_tag_id'), 'contact_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_contact_tags_workspace_id'), 'contact_tags', ['workspace_id'], unique=False)
    op.create_table('csat_responses',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('conversation_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('contact_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_csat_responses_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_csat_responses_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_csat_responses')),
    sa.UniqueConstraint('workspace_id', 'conversation_id', name='uq_csat_ws_conversation')
    )
    op.create_index(op.f('ix_csat_responses_contact_id'), 'csat_responses', ['contact_id'], unique=False)
    op.create_index(op.f('ix_csat_responses_conversation_id'), 'csat_responses', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_csat_responses_workspace_id'), 'csat_responses', ['workspace_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('source_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('uri', sa.String(length=1000), nullable=True),
    sa.Column('mime', sa.String(length=120), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('meta', app.core.db.PortableJSON(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], name=op.f('fk_documents_source_id_knowledge_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_documents_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_source_id'), 'documents', ['source_id'], unique=False)
    op.create_index(op.f('ix_documents_workspace_id'), 'documents', ['workspace_id'], unique=False)
    op.create_index('ix_documents_ws_source', 'documents', ['workspace_id', 'source_id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('custom_role_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('token', sa.String(length=80), nullable=False),
    sa.Column('invited_by', app.core.db.GUID(length=36), nullable=True),
    sa.Column('expires_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['custom_role_id'], ['custom_roles.id'], name=op.f('fk_invitations_custom_role_id_custom_roles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_invitations_invited_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_invitations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitations'))
    )
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.create_index(op.f('ix_invitations_workspace_id'), 'invitations', ['workspace_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('user_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('custom_role_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['custom_role_id'], ['custom_roles.id'], name=op.f('fk_memberships_custom_role_id_custom_roles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_memberships_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_memberships_ws_user')
    )
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_memberships_workspace_id'), 'memberships', ['workspace_id'], unique=False)
    op.create_table('team_members',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('team_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('user_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_members_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_team_members_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_team_members_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_members')),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_members_pair')
    )
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_team_members_workspace_id'), 'team_members', ['workspace_id'], unique=False)
    op.create_table('tour_events',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('tour_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('contact_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('event', sa.String(length=20), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=True),
    sa.Column('meta', app.core.db.PortableJSON(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], name=op.f('fk_tour_events_tour_id_tours'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_tour_events_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tour_events'))
    )
    op.create_index(op.f('ix_tour_events_contact_id'), 'tour_events', ['contact_id'], unique=False)
    op.create_index('ix_tour_events_tour_created', 'tour_events', ['tour_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_tour_events_tour_id'), 'tour_events', ['tour_id'], unique=False)
    op.create_index(op.f('ix_tour_events_workspace_id'), 'tour_events', ['workspace_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('webhook_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('event_name', sa.String(length=50), nullable=False),
    sa.Column('payload', app.core.db.PortableJSON(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], name=op.f('fk_webhook_deliveries_webhook_id_webhooks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_webhook_deliveries_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_deliveries'))
    )
    op.create_index('ix_webhook_deliveries_webhook_created', 'webhook_deliveries', ['webhook_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_webhook_id'), 'webhook_deliveries', ['webhook_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_workspace_id'), 'webhook_deliveries', ['workspace_id'], unique=False)
    op.create_table('agent_steps',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('run_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('input', app.core.db.PortableJSON(), nullable=False),
    sa.Column('output', app.core.db.PortableJSON(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_agent_steps_run_id_agent_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_agent_steps_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_steps'))
    )
    op.create_index(op.f('ix_agent_steps_run_id'), 'agent_steps', ['run_id'], unique=False)
    op.create_index('ix_agent_steps_run_ord', 'agent_steps', ['run_id', 'ord'], unique=False)
    op.create_index(op.f('ix_agent_steps_workspace_id'), 'agent_steps', ['workspace_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('run_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('conversation_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('agent_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('tool_key', sa.String(length=120), nullable=False),
    sa.Column('tool_input', app.core.db.PortableJSON(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('requested_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('decided_by', app.core.db.GUID(length=36), nullable=True),
    sa.Column('decided_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_approval_requests_run_id_agent_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_approval_requests_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_requests'))
    )
    op.create_index(op.f('ix_approval_requests_run_id'), 'approval_requests', ['run_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_workspace_id'), 'approval_requests', ['workspace_id'], unique=False)
    op.create_index('ix_approval_requests_ws_status', 'approval_requests', ['workspace_id', 'status'], unique=False)
    op.create_table('chunks',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('document_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', app.core.db.EmbeddingVector(), nullable=True),
    sa.Column('meta', app.core.db.PortableJSON(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_chunks_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks'))
    )
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunks_workspace_id'), 'chunks', ['workspace_id'], unique=False)
    op.create_index('ix_chunks_ws_doc_ord', 'chunks', ['workspace_id', 'document_id', 'ord'], unique=False)
    op.create_table('conversations',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('inbox_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('contact_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('contact_inbox_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('snoozed_until', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('assignee_user_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('team_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('subject', sa.String(length=400), nullable=True),
    sa.Column('attributes', app.core.db.PortableJSON(), nullable=False),
    sa.Column('ai_agent_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('waiting_since', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('first_reply_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('agent_last_seen_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('contact_last_seen_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('csat_requested', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], name=op.f('fk_conversations_assignee_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_conversations_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_inbox_id'], ['contact_inboxes.id'], name=op.f('fk_conversations_contact_inbox_id_contact_inboxes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inbox_id'], ['inboxes.id'], name=op.f('fk_conversations_inbox_id_inboxes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_conversations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    sa.UniqueConstraint('workspace_id', 'number', name='uq_conversations_ws_number')
    )
    op.create_index(op.f('ix_conversations_contact_id'), 'conversations', ['contact_id'], unique=False)
    op.create_index(op.f('ix_conversations_inbox_id'), 'conversations', ['inbox_id'], unique=False)
    op.create_index(op.f('ix_conversations_workspace_id'), 'conversations', ['workspace_id'], unique=False)
    op.create_index('ix_conversations_ws_assignee', 'conversations', ['workspace_id', 'assignee_user_id'], unique=False)
    op.create_index('ix_conversations_ws_contact', 'conversations', ['workspace_id', 'contact_id'], unique=False)
    op.create_index('ix_conversations_ws_status_activity', 'conversations', ['workspace_id', 'status', 'last_activity_at'], unique=False)
    op.create_table('conversation_tags',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('conversation_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('tag_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_tags_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_conversation_tags_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_tags')),
    sa.UniqueConstraint('conversation_id', 'tag_id', name='uq_conversation_tags_pair')
    )
    op.create_index(op.f('ix_conversation_tags_conversation_id'), 'conversation_tags', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_tags_tag_id'), 'conversation_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_conversation_tags_workspace_id'), 'conversation_tags', ['workspace_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('conversation_id', app.core.db.GUID(length=36), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('visibility', sa.String(length=10), nullable=False),
    sa.Column('author_type', sa.String(length=20), nullable=False),
    sa.Column('author_id', app.core.db.GUID(length=36), nullable=True),
    sa.Column('author_name', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachments', app.core.db.PortableJSON(), nullable=False),
    sa.Column('source_id', sa.String(length=300), nullable=True),
    sa.Column('delivery_status', sa.String(length=10), nullable=True),
    sa.Column('delivery_error', sa.Text(), nullable=True),
    sa.Column('meta', app.core.db.PortableJSON(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', app.core.db.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_messages_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('conversation_id', 'source_id', name='uq_messages_conversation_source')
    )
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_workspace_id'), 'messages', ['workspace_id'], unique=False)
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_chunks_fts ON chunks "
        "USING GIN (to_tsvector('english', content))"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_contacts_name_trgm ON contacts "
        "USING GIN (name gin_trgm_ops)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_workspace_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversation_tags_workspace_id'), table_name='conversation_tags')
    op.drop_index(op.f('ix_conversation_tags_tag_id'), table_name='conversation_tags')
    op.drop_index(op.f('ix_conversation_tags_conversation_id'), table_name='conversation_tags')
    op.drop_table('conversation_tags')
    op.drop_index('ix_conversations_ws_status_activity', table_name='conversations')
    op.drop_index('ix_conversations_ws_contact', table_name='conversations')
    op.drop_index('ix_conversations_ws_assignee', table_name='conversations')
    op.drop_index(op.f('ix_conversations_workspace_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_inbox_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_contact_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_chunks_ws_doc_ord', table_name='chunks')
    op.drop_index(op.f('ix_chunks_workspace_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('ix_approval_requests_ws_status', table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_workspace_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_run_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_agent_steps_workspace_id'), table_name='agent_steps')
    op.drop_index('ix_agent_steps_run_ord', table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_run_id'), table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_index(op.f('ix_webhook_deliveries_workspace_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_webhook_id'), table_name='webhook_deliveries')
    op.drop_index('ix_webhook_deliveries_webhook_created', table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_tour_events_workspace_id'), table_name='tour_events')
    op.drop_index(op.f('ix_tour_events_tour_id'), table_name='tour_events')
    op.drop_index('ix_tour_events_tour_created', table_name='tour_events')
    op.drop_index(op.f('ix_tour_events_contact_id'), table_name='tour_events')
    op.drop_table('tour_events')
    op.drop_index(op.f('ix_team_members_workspace_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_memberships_workspace_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_invitations_workspace_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index('ix_documents_ws_source', table_name='documents')
    op.drop_index(op.f('ix_documents_workspace_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_source_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_csat_responses_workspace_id'), table_name='csat_responses')
    op.drop_index(op.f('ix_csat_responses_conversation_id'), table_name='csat_responses')
    op.drop_index(op.f('ix_csat_responses_contact_id'), table_name='csat_responses')
    op.drop_table('csat_responses')
    op.drop_index(op.f('ix_contact_tags_workspace_id'), table_name='contact_tags')
    op.drop_index(op.f('ix_contact_tags_tag_id'), table_name='contact_tags')
    op.drop_index(op.f('ix_contact_tags_contact_id'), table_name='contact_tags')
    op.drop_table('contact_tags')
    op.drop_index(op.f('ix_contact_notes_workspace_id'), table_name='contact_notes')
    op.drop_index(op.f('ix_contact_notes_contact_id'), table_name='contact_notes')
    op.drop_table('contact_notes')
    op.drop_index(op.f('ix_contact_inboxes_workspace_id'), table_name='contact_inboxes')
    op.drop_index(op.f('ix_contact_inboxes_inbox_id'), table_name='contact_inboxes')
    op.drop_index(op.f('ix_contact_inboxes_contact_id'), table_name='contact_inboxes')
    op.drop_table('contact_inboxes')
    op.drop_index(op.f('ix_contact_events_workspace_id'), table_name='contact_events')
    op.drop_index(op.f('ix_contact_events_contact_id'), table_name='contact_events')
    op.drop_index('ix_contact_events_contact_created', table_name='contact_events')
    op.drop_table('contact_events')
    op.drop_index(op.f('ix_articles_workspace_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_collection_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_ai_models_workspace_id'), table_name='ai_models')
    op.drop_index(op.f('ix_ai_models_provider_id'), table_name='ai_models')
    op.drop_table('ai_models')
    op.drop_index('ix_agent_runs_ws_status', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_workspace_id'), table_name='agent_runs')
    op.drop_index('ix_agent_runs_conversation', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_webhooks_workspace_id'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_tours_workspace_id'), table_name='tours')
    op.drop_table('tours')
    op.drop_index(op.f('ix_teams_workspace_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_tags_workspace_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_segments_workspace_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_index('ix_notifications_ws_user_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_workspace_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_knowledge_sources_workspace_id'), table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    op.drop_index(op.f('ix_inboxes_workspace_id'), table_name='inboxes')
    op.drop_index(op.f('ix_inboxes_widget_key'), table_name='inboxes')
    op.drop_table('inboxes')
    op.drop_index(op.f('ix_custom_roles_workspace_id'), table_name='custom_roles')
    op.drop_table('custom_roles')
    op.drop_index(op.f('ix_custom_actions_workspace_id'), table_name='custom_actions')
    op.drop_table('custom_actions')
    op.drop_table('conversation_counters')
    op.drop_index('ix_contacts_ws_last_seen', table_name='contacts')
    op.drop_index('ix_contacts_ws_email', table_name='contacts')
    op.drop_index(op.f('ix_contacts_workspace_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_canned_responses_workspace_id'), table_name='canned_responses')
    op.drop_table('canned_responses')
    op.drop_index('ix_automation_rules_ws_event_enabled', table_name='automation_rules')
    op.drop_index(op.f('ix_automation_rules_workspace_id'), table_name='automation_rules')
    op.drop_table('automation_rules')
    op.drop_index('ix_audit_logs_ws_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_article_collections_workspace_id'), table_name='article_collections')
    op.drop_table('article_collections')
    op.drop_index(op.f('ix_api_keys_workspace_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_hashed_key'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_ai_providers_workspace_id'), table_name='ai_providers')
    op.drop_table('ai_providers')
    op.drop_index(op.f('ix_agents_workspace_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
